# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    executor: default-executor
    steps:
      - checkout  # Check out your source code

      - run:
          name: Build Docker Image
          command: docker build -t tests .

      - run:
          name: Run Docker Container
          command: docker run tests

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
#workflows:
#  tests-workflow:
#    jobs:
#      - build image
#      - mvn tests
